language: cpp
dist: bionic

script:
   - set -e
   - cmake .
   - cmake --build .
deploy:
  - provider: bintray
    file: bintray.json
    user: khatrox
    key: ${BINTRAY_API_KEY}
    skip_cleanup: true